sudo: false
language: android
branches:
    only:
        - master
cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle
jdk:
    - oraclejdk8
android:
    components:
        - tools
        - build-tools-25.0.2
        - android-25
        - extra-android-support
        - extra-google-m2repository
        - extra-android-m2repository
before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
script: ./gradlew clean assembleStandardRelease testStandardRelease -PdisablePreDex
notifications:
    email: false
